Use env var ENGI__DISABLEGITHUBINTEGRATION to skip GitHub checks
engi-network/engi-blockchain-gql pull request #1
Opened 2022-12-14 01:25 UTC by cck197

I want to skip the GitHub checks for end-to-end integration testing. 

With this change, via a Python CLI `pytest` test I can:
1. Submit an analysis to the `analysis.submit` mutation
2. See the analysis request come back via the SNS -> SQS fanout
3. Process the request in `app.py`
4. Verify the appropriate changes in RavenDB

I couldn't figure out the ASP.NET `appsettings.json` interface. You'll probably want to eliminate my environment variable and use the configuration provider instead. Although, I'm not a big fan of the language-specific hierarchical configuration files as it's nice to [manage all the config in one place](https://12factor.net/config).

2022-12-15 19:23 UTC, georgiosd requested changes

2022-12-15 19:23 UTC, georgiosd commented on engi-server/Types/Analysis/AnalysisMutations.cs
> +        var skipGitHub = Environment.GetEnvironmentVariable("ENGI__DISABLEGITHUBINTEGRATION");
The right way to do this is to add `DisableGithubIntegration` in `EngiOptions` and set the default value to `false` in `appsettings.json`, then use `bool.Parse` to convert to boolean before checking if the flag is there.

2022-12-15 19:30 UTC, garrettmaring commented
Patching the DB for integration tests elsewhere sounds better than the source changes here. @cck197 and I discussed making a GH apps & users for tests as well.

2022-12-15 21:31 UTC, georgiosd commented
Okay, are we closing this? Want me to make a sample bash file or whatever with the patch?

2022-12-18 13:33 UTC, garrettmaring commented
Let's wait for @cck197 reply

2022-12-21 17:04 UTC, cck197 commented
Patching the user in RavenDB works! Thank you.

Closing.

2022-12-21 17:04 UTC, closed without merging